import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

/**
 * POST /api/party/create
 *
 * Creates a new party game lobby in 'waiting' state.
 * Share the returned gameId with other players so they can join from their browser.
 *
 * Response: { gameId: string }
 */
export async function POST(req: Request) {
  try {
    // get the request body as JSON, default to empty object if parsing fails
    const body = await req.json().catch(() => ({}));
    // get the countdownMinutes from the request body, default to 1 if not provided
    const countdownMinutes = typeof body.countdownMinutes === 'number' ? body.countdownMinutes : 1;
    // get the playerCount from the request body, default to 3 if not provided
    const playerCount = typeof body.playerCount === 'number' ? body.playerCount : 3;

    // create a new game in the database. await the result and return the gameId in the response. gameId is automatically generated by Supabase as a UUID.
    // the countdown_minutes column is set by player to indicate how much time they have to write a description of the artifact in minutes.
    const game = await db.party_games.create({
      data: { countdown_minutes: countdownMinutes, number_players: playerCount },
    });
    // return the gameId in the response with status 201 Created
    return NextResponse.json({ gameId: game.id }, { status: 201 });
  } catch (err) {
    // log the error to the console and return a 503 Service Unavailable response with an error message
    console.error('[party/create] DB error:', err);
    return NextResponse.json({ error: 'Failed to create game' }, { status: 503 });
  }
}
